/* search-index.js — card data for cross-deck search on the home page.
   Keep in sync with each deck's CARDS array when you add or edit cards. */
var SEARCH_INDEX = [
  {
    deckId: 'lets-learn-claude-code',
    deckTitle: "Let's Learn Claude Code",
    cards: [
      { q: 'What is Claude Code?', a: 'An AI coding agent — not just a chat tool — that can autonomously read files, write code, run commands, and operate across your entire codebase inside your terminal or IDE.' },
      { q: 'How is Claude Code different from a chat-based AI tool?', a: 'A chat tool only converses. Claude Code is an agentic system: it takes actions — reading files, running tests, editing code, executing commands — in an autonomous loop until the task is done.' },
      { q: 'What is the agentic loop?', a: 'The core mechanism where Claude Code repeatedly reasons, calls tools (read file, run command, edit code), observes the result, and decides the next step — cycling until the goal is achieved.' },
      { q: 'What platforms and editors does Claude Code support?', a: 'Terminal (any shell), VS Code, JetBrains IDEs, the Claude desktop app, and a web-based interface.' },
      { q: 'What are the prerequisites for using Claude Code?', a: 'Basic familiarity with a code editor and the command line, plus a Claude Pro, Max, or Enterprise subscription — or an Anthropic API key.' },
      { q: 'What is the four-phase Claude Code workflow?', a: 'Explore → Plan → Code → Commit. First understand the codebase, then plan the approach, then implement, then commit with a clear message.' },
      { q: 'What happens in the Explore phase?', a: 'Claude Code reads and searches the codebase to build context — understanding file structure, existing patterns, dependencies, and relevant code before touching anything.' },
      { q: 'What happens in the Plan phase?', a: 'Claude Code (or you in Plan Mode) lays out the steps to complete the task — which files to change, what logic to add, and in what order — before writing any code.' },
      { q: 'What is Plan Mode in Claude Code?', a: 'A mode where Claude Code outlines its intended approach and waits for your approval before executing any actions, giving you a chance to redirect or refine the plan.' },
      { q: 'What happens in the Code phase?', a: 'Claude Code implements the plan — creating or editing files, writing code, and running commands — guided by what it learned in Explore and decided in Plan.' },
      { q: 'What happens in the Commit phase?', a: 'Claude Code stages changes and creates a descriptive git commit, summarising what was changed and why, completing the development loop.' },
      { q: 'What is "approval mode" in Claude Code?', a: 'A setting where Claude Code asks for your confirmation before executing each action (file write, command run, etc.), giving you fine-grained control over what it does.' },
      { q: 'What is auto-accept in Claude Code?', a: 'A mode that lets Claude Code execute actions without pausing for approval each time — useful for trusted, well-understood tasks where you want uninterrupted flow.' },
      { q: 'What is the CLAUDE.md file?', a: 'A markdown file in your project root that gives Claude Code persistent memory about the project — conventions, architecture, commands to run, things to avoid — loaded automatically each session.' },
      { q: 'Why is CLAUDE.md useful?', a: 'Without it, you must re-explain project context every session. CLAUDE.md lets Claude Code know your stack, coding standards, test commands, and any project-specific rules from the start.' },
      { q: 'What are Subagents in Claude Code?', a: 'Delegated agents spun up to handle a sub-task independently, so the main agent\'s context window stays focused and uncluttered while parallel or isolated work is done separately.' },
      { q: 'What are Skills in Claude Code?', a: 'Pre-built or custom slash-command capabilities that extend Claude Code\'s default behaviour — for example /code-review, /simplify, or a custom workflow you define.' },
      { q: 'What are MCP Servers in Claude Code?', a: 'Model Context Protocol servers that connect Claude Code to external tools and data sources — databases, APIs, services — so it can retrieve live information or trigger external actions.' },
      { q: 'What are Hooks in Claude Code?', a: 'Shell commands that run automatically at specific events (e.g. before a tool call, after a commit) to enforce formatting, block certain commands, or trigger notifications deterministically.' },
      { q: 'What is the /compact command?', a: 'Optimises token usage by summarising older parts of the conversation, reducing context window consumption so you can keep working on long tasks without hitting the limit.' },
      { q: 'What is the /clear command?', a: 'Removes sections of context from the conversation — useful for wiping irrelevant history and giving Claude Code a cleaner working state for a new sub-task.' },
      { q: 'What is the /context command?', a: 'Shows the current state of the context window — what Claude Code can currently "see" — so you can understand what information is in scope.' },
      { q: 'What are Tools & Permissions in Claude Code?', a: 'The system that controls which actions Claude Code is allowed to take — reading files, running shell commands, making network requests — configurable per project or globally.' },
      { q: 'How does Claude Code help with code review?', a: 'It can read a diff or branch, identify bugs, spot style issues, suggest simplifications, and even post inline comments on a GitHub PR — all from the terminal.' },
      { q: 'What is context window management and why does it matter in Claude Code?', a: 'Managing how much text is in the active conversation. A full context window slows performance and can cause Claude Code to lose earlier details — /compact and /clear help keep it efficient.' }
    ]
  },
  {
    deckId: 'get-started-with-claude',
    deckTitle: 'Get Started with Claude',
    cards: [
      { q: 'What is Claude?', a: 'An AI assistant made by Anthropic, designed to be helpful, harmless, and honest. It can write, analyse, code, research, and hold extended conversations.' },
      { q: 'What are the three pillars of Claude\'s design?', a: 'Helpful, Harmless, and Honest — Claude is built to be useful to users while avoiding harm and being truthful.' },
      { q: 'What is a prompt?', a: 'Text you send to Claude to start or continue a conversation. A good prompt is clear, specific, and provides enough context for Claude to give a useful response.' },
      { q: 'How do you get better results from Claude?', a: 'Be specific about your goal, provide relevant context, specify the format you want, and iterate — ask Claude to revise or expand if the first answer isn\'t quite right.' },
      { q: 'What are the three main modes in the Claude desktop app?', a: 'Chat (conversational Q&A), Cowork (collaborative document creation), and Code (coding assistance and debugging).' },
      { q: 'What is the Chat mode used for?', a: 'Open-ended conversation — asking questions, brainstorming, summarising content, getting explanations, or any general task.' },
      { q: 'What is Cowork mode in the Claude desktop app?', a: 'A collaborative workspace where you and Claude work together on documents, drafts, or structured content in real time.' },
      { q: 'What is Code mode in the Claude desktop app?', a: 'A specialised environment for writing, reviewing, debugging, and explaining code across many programming languages.' },
      { q: 'What are Projects in Claude?', a: 'A way to organise related conversations, files, and instructions in one place so Claude has consistent context across multiple sessions on the same topic.' },
      { q: 'What is the benefit of using Projects?', a: 'Claude remembers the context, uploaded documents, and custom instructions you set for that project — no need to re-explain your situation each session.' },
      { q: 'What are Artifacts in Claude?', a: 'Standalone, reusable outputs Claude creates — such as a document, code file, table, or diagram — that you can copy, download, or build on.' },
      { q: 'How do you create an Artifact?', a: 'Ask Claude to produce a self-contained output (e.g. "write a Python script" or "create a report"). Claude renders it in a separate panel so you can work with it independently.' },
      { q: 'What are Skills in Claude?', a: 'Pre-built or custom capabilities that extend what Claude can do — for example, browsing the web, running code, or following a specific workflow you\'ve defined.' },
      { q: 'What does "Connecting your tools" mean in Claude?', a: 'Integrating Claude with external apps and services (calendar, email, Slack, etc.) so it can retrieve information and take actions across your workflow.' },
      { q: 'What is Enterprise Search in Claude?', a: 'A feature that lets Claude search across your organisation\'s connected data sources (documents, wikis, emails) to find relevant information and include it in answers.' },
      { q: 'What is Research Mode in Claude?', a: 'A deep-dive capability where Claude performs multiple searches and synthesises information from many sources to produce a thorough, cited research report.' },
      { q: 'When should you use Research Mode?', a: 'For complex questions that benefit from broad information gathering — competitive analysis, literature reviews, market research, or any topic where depth matters.' },
      { q: 'What is the context window?', a: 'The maximum amount of text (your messages + Claude\'s replies + any files) that Claude can process in one conversation. Information outside the window is not visible to Claude.' },
      { q: 'How can you use Claude by role — e.g. as a marketer?', a: 'Marketers can use Claude to draft campaigns, write copy, analyse customer feedback, and brainstorm ideas — prompting Claude with role-specific context for tailored output.' },
      { q: 'How can developers use Claude?', a: 'For code generation, debugging, code review, writing tests, explaining legacy code, and getting documentation — in Code mode or via the API.' },
      { q: 'How can executives or managers use Claude?', a: 'To summarise reports, prepare talking points, draft emails, analyse data, and get quick briefings — saving time on high-volume reading and writing tasks.' },
      { q: 'What are some everyday use cases for Claude?', a: 'Writing and editing, summarising long documents, brainstorming, answering questions, drafting emails, explaining complex topics, and coding assistance.' },
      { q: 'What should you do when Claude\'s answer is not quite right?', a: 'Iterate — tell Claude what was off ("too long", "wrong tone", "focus on X instead") and it will revise. Good prompting is a conversation, not a one-shot command.' },
      { q: 'Does Claude require an Anthropic account to take the Claude 101 course?', a: 'No — the course on Skilljar is free to access with just an email registration, separate from an Anthropic account.' },
      { q: 'What can you earn at the end of the Claude 101 course?', a: 'A certificate of completion from Anthropic, demonstrating proficiency with Claude\'s core features and everyday use cases.' }
    ]
  },
  {
    deckId: 'claude-cowork',
    deckTitle: 'Introduction to Claude Cowork',
    cards: [
      { q: 'What is Claude Cowork?', a: 'A mode where Claude works directly with your files, folders, and apps — reading, editing, and producing real outputs on your machine — rather than just having a conversation.' },
      { q: 'What is the core difference between Claude Chat and Claude Cowork?', a: 'Chat is conversational — you exchange messages. Cowork is a working session — you assign a task, Claude plans and executes it on your actual files and apps, and you steer along the way.' },
      { q: 'What are "real outputs" in Cowork?', a: 'Actual changes to your files, folders, and apps — edited documents, created spreadsheets, filled forms, organised folders — not just text responses you have to copy-paste yourself.' },
      { q: 'What happens when you assign a task in Cowork?', a: 'Claude reads the task and context, forms an execution plan, carries out the steps (reading, editing, producing outputs), and pauses for your direction when needed.' },
      { q: 'What does "course correction" mean in Cowork?', a: 'Steering Claude mid-task — providing feedback, clarifying intent, or redirecting steps while a multi-step job is in progress, rather than only reviewing the final output.' },
      { q: 'How does context influence Claude\'s planning in Cowork?', a: 'The more context Claude has about your goal, preferred style, and past work, the more accurately it plans the steps and produces outputs that match what you actually need.' },
      { q: 'What is standing context in Cowork?', a: 'Persistent instructions or project information that Claude carries into every Cowork session, so you don\'t have to re-explain your preferences, team conventions, or project background each time.' },
      { q: 'How do you establish standing context in Cowork?', a: 'Through global instructions (applied to all sessions) and Projects (applied to a specific topic or workflow), both of which Claude reads automatically when a session starts.' },
      { q: 'What are global instructions in Cowork?', a: 'Persistent preferences you set once that apply to every Cowork session — e.g. always use British English, never delete originals, save outputs to a specific folder.' },
      { q: 'What are Projects in Cowork?', a: 'Scoped workspaces with their own standing context, files, and instructions for a specific ongoing task or team — Claude uses that project\'s context whenever you work within it.' },
      { q: 'What are Skills in Cowork?', a: 'Saved, reusable task workflows you define — e.g. "format this report in our template" or "summarise meeting notes and email the team" — that Claude can execute on command.' },
      { q: 'What are Plugins in Cowork?', a: 'Extensions that encode team expertise and procedures into Cowork, enabling Claude to follow your organisation\'s specific processes automatically without being re-instructed each time.' },
      { q: 'How do you validate custom Skills and Plugins?', a: 'Run them on test inputs, review the outputs against your expected results, and refine the instructions until Claude consistently performs the task correctly before sharing with the team.' },
      { q: 'How do you share Skills or Plugins with teammates?', a: 'Export and distribute the build so team members can install the same skill or plugin, ensuring everyone benefits from the same encoded workflow without rebuilding it individually.' },
      { q: 'How does Cowork integrate with Chrome?', a: 'A Chrome extension lets Claude access and interact with web-based apps directly in the browser — reading page content, filling forms, navigating, and automating browser-based tasks.' },
      { q: 'How does Cowork integrate with Microsoft 365?', a: 'Claude can read and edit Word documents, Excel spreadsheets, Outlook emails, and other M365 files — treating them as first-class working documents rather than attachments to describe.' },
      { q: 'What platforms does Cowork support?', a: 'Local files and folders on your machine, Chrome browser (via extension), Microsoft 365 applications, and additional platforms through plugins.' },
      { q: 'What are best practices for collaborative safety in Cowork?', a: 'Review Claude\'s plan before it executes destructive actions, keep backups of important files, validate skills before sharing, and set clear instructions about what Claude should never do.' },
      { q: 'How should you manage longer-running tasks in Cowork?', a: 'Break them into phases, review outputs at each milestone, use course corrections to stay aligned, and avoid giving Claude an overly broad mandate without checkpoints.' },
      { q: 'What is the goal of a first Cowork task?', a: 'To build foundational confidence — pick a low-stakes, self-contained task so you can observe how Claude plans, executes, and handles your files before trusting it with critical work.' },
      { q: 'How do you get faster, higher-quality results in Cowork?', a: 'Invest in standing context (global instructions + projects), build reusable skills for repeated workflows, and give precise upfront context so Claude plans accurately from the start.' },
      { q: 'What is the typical progression for a new Cowork user?', a: 'Initial launch → first end-to-end task → learning to steer with course corrections → customising with instructions and skills → integrating plugins for team workflows → confident daily use.' },
      { q: 'Why is upfront context important in Cowork vs Chat?', a: 'In Chat a clarification mid-conversation is easy. In Cowork, Claude may have already edited files by the time you clarify — good upfront context prevents costly mid-task rework.' },
      { q: 'What kinds of files can Cowork read and edit?', a: 'Documents (Word, PDF, text), spreadsheets (Excel, CSV), emails, folders, and web content in Chrome — essentially any file type your machine can open that a plugin or integration covers.' },
      { q: 'What makes Cowork suitable for team use?', a: 'Shareable skills and plugins encode team expertise once and deploy it to everyone, so the whole team benefits from consistent, high-quality automated workflows without individual setup.' }
    ]
  }
];
